# Файл конфигурации для air.
# Документация: https://github.com/cosmtrek/air
# Это базовая конфигурация для начала работы.

# Корневая директория вашего проекта относительно этого файла.
root = "." 
# Директория для временных файлов, включая скомпилированный бинарник.
tmp_dir = "tmp"

[build]
# Команда для сборки вашего приложения.
cmd = "go build -o ./tmp/main ."
# Путь к скомпилированному бинарнику, который air будет запускать.
bin = "./tmp/main"

# Расширения файлов, за которыми air будет следить.
include_ext = ["go", "tpl", "tmpl", "html"]
# Директории, которые нужно игнорировать при отслеживании изменений.
exclude_dir = ["assets", "tmp", "vendor"]
# Файлы, которые нужно игнорировать.
exclude_file = []
# Логировать ошибки сборки в файл.
log = "air_errors.log"
# Задержка перед перезапуском после обнаружения изменений (в миллисекундах).
delay = 1000 
# Останавливаться, если при сборке возникла ошибка.
stop_on_error = true

[log]
# Показывать время в логах air.
time = true

[color]
# Цветовая схема для логов, чтобы было удобнее читать.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Удалять временные файлы (tmp_dir) при выходе из air.
clean_on_exit = true 